# file: .github/workflows/preview.yaml
on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: [self-hosted]
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        url: ${{ secrets.OKTETO_URL }}

    - name: Create namespace
      uses: okteto/create-namespace@master
      with:
        namespace: pr-${{ github.event.number }}

    - name: Deploy Application
      uses: okteto/pipeline@v0.3
      with:
        name: pr-${{ github.event.number }}

    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Preview environment available at https://frontend-pr-${{ github.event.number }}.sf.okteto.net"